/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;
import Ficha.Player;
import Ficha.ficha;
import java.util.ArrayList;
/**
 *
 * @author William
 */
public class Estratego extends javax.swing.JFrame {

     ficha tablero[][];
     ArrayList<Player> jugadores;
        int f1,c1,f2,c2;
    public Estratego() {
        initComponents();
        tablero=new ficha[10][10];
        jugadores=new ArrayList<>();
        jp1.setVisible(true);
        jp3.setVisible(false);
        jp4.setVisible(false);   
        jp2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        jp2 = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();
        jp3 = new javax.swing.JPanel();
        btnIpartida = new javax.swing.JButton();
        jp4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1658, 1940));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp1.setPreferredSize(new java.awt.Dimension(1628, 930));
        jp1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn1.setText("Login");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jp1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 400, -1, -1));

        btn2.setText("Create Player");
        jp1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 441, -1, -1));

        getContentPane().add(jp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jp2.setPreferredSize(new java.awt.Dimension(1628, 930));
        jp2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jp2.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        getContentPane().add(jp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 999, -1, -1));

        jp3.setPreferredSize(new java.awt.Dimension(1628, 930));
        jp3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIpartida.setText("Iniciar Partida");
        btnIpartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIpartidaActionPerformed(evt);
            }
        });
        jp3.add(btnIpartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        getContentPane().add(jp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1, -1, -1));

        jp4.setPreferredSize(new java.awt.Dimension(1628, 930));
        jp4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
       jp1.setVisible(false);
       jp3.setVisible(false);
       jp4.setVisible(false);   
       jp2.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        jp2.setVisible(false);
        jp3.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnIpartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIpartidaActionPerformed
        jp3.setVisible(false);
        jp4.setVisible(true);
    }//GEN-LAST:event_btnIpartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    
                                         

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estratego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estratego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estratego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estratego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estratego().setVisible(true);
            }
        });
    }
    
                            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIpartida;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    // End of variables declaration//GEN-END:variables
}
